version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bodo-front-prod
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
